# Config file for ricochet-group

publicgroup: true

# setup admin users by listing their ricochet ids, like so:
#   admins:
#    - aaaaaaaaaaaaaaaa

# if publicgroup is true, anyone is allowed to connect to your chat group
# if publicgroup is false, list ricochet ids of allowed users like so:
#   allowedusers:
#    - aaaaaaaaaaaaaaaa
#    - bbbbbbbbbbbbbbbb

welcomemsg: "*** welcome to ricochet group chat."

# specify how to connect to tor's control socket like so:
#   torcontrol: 127.0.0.1:9051
#   torcontroltype: tcp4
# or:
#   torcontrol: /var/run/tor/control
#   torcontroltype: unix
# and set the authentication string if applicable:
#   torcontrolauthentication: foo
