# Config file for ricochet-group

publicgroup: true

# setup admin users like so:
#    admins:
#     - it2j3z6t6ksumpzd

# if publicgroup is true, anyone is allowed to connect to your chat group
# if publicgroup is false, list allowed users like so:
#   allowedusers:
#    - p3znpgn2rzeakrk7
#    - it2j3z6t6ksumpzd

welcomemsg: "*** welcome to ricochet group chat."

# specify how to connect to tor's control socket like so:
#   torcontrol: 127.0.0.1:9051
#   torcontroltype: tcp4
# or:
#   torcontrol: /var/run/tor/control
#   torcontroltype: unix
# and set the authentication string if applicable:
#   torcontrolauthentication: foo
